unpack: Make detection logic more compact and flexible. Allow for semi-automated guessing for container format in order to easily provide some basic support for unknown container types

diff --git a/bin/unwrap b/bin/unwrap
--- a/bin/unwrap
+++ b/bin/unwrap
@@ -7,6 +7,7 @@
 #%
 #%Recursively unpack containers. That is, if there are other container files inside they will also be unpacked.
 #%Supported container formats (package requirements apply)
+#%- 3mf -> requires 'unzip'
 #%- zipfiles (.zip) -> requires 'unzip'
 #%- gzipped and pure tarballs (.tar, .tgz, .tar.gz) -> requires 'tar'
 #%- xz packed tarballs (.tar.xz) -> requires 'tar' and 'xz'
@@ -31,92 +32,196 @@
 #%-v            - increase verbosity
 #%-H <hashfile> - store SHA256 hashes of all extracted files into <hashfile>
 #%-x            - remove container after extraction
-#%-o		- unwrap once, leave containers inside containers
+#%-G            - use file(1) and simple suffix detection logic to try and guess the container format
+#%-o            - unwrap once, leave containers inside containers
 #%-h            - this help text
 #%
 #%Author: Maciej Grela <enki@fsck.pl>
 
+# Reference: https://stackoverflow.com/a/17841619
+function join_by { local IFS="$1"; shift; echo "$*"; }
+
+#
+# log4bash
+#
+log() { echo $* 1>&2; }
+error() { log $*; }
+verbose() { [ -n "$verbose" ] && log $*; }
+fatal() { log $*; exit 1; }
+
 destdir=.
 
-while getopts C:vxohH: opt; do
+while getopts C:vxohGH: opt; do
     case $opt in
         C) destdir="$OPTARG";;
-	v) verbose=1;;
-	x) remove_container=1;;
-  H) hash_filename="$OPTARG";;
-	o) unwrap_once=1;;
-	h) grep "^#%" $0 | sed 's/^#%//';;
+        v) verbose=1;;
+        x) remove_container=1;;
+        G) guess=1;;
+        H) hash_filename="$OPTARG";;
+        o) unwrap_once=1;;
+        h) grep "^#%" $0 | sed 's/^#%//';;
         ?) exit 1;;
     esac
 done
 shift $((OPTIND-1))
 
+
+detect_suffix() {
+    container="$1"; shift;
+
+    if [ -n "$guess" ]; then
+        suffix="${container##*.}"
+
+        #
+        # Handle common problems with the above simplistic approach
+        #
+        [ -z "$suffix" ] && suffix='<unknown>'
+        [ ".$suffix" = "$container" ] && suffix='<unknown>'
+
+        if [ "$suffix" != '<unknown>' ]; then
+            suffix=".$suffix"
+            verbose "$container: guessed suffix '$suffix'"
+        fi
+    else
+        suffix='<unknown>'
+    fi
+
+    case "$container" in
+        *.3mf) suffix=".3mf";;
+        *.zip) suffix=".zip";;
+        *.jar) suffix=".jar";;
+        *.war) suffix=".war";;
+        *.ear) suffix=".ear";;
+        *.apk) suffix=".apk";;
+        *.xapk) suffix=".xapk";;
+        *.ipa) suffix=".ipa";;
+        *.docx) suffix=".docx";;
+        *.tar) suffix=".tar";;
+        *.tar.gz) suffix=".tar.gz";;
+        *.tar.bz2) suffix=".tar.bz2";;
+        *.tar.xz) suffix=".tar.xz";;
+        *.tgz) suffix=".tgz";;
+        *.tbz2) suffix=".tbz2";;
+        *.rar) suffix=".rar";;
+        *.7z) suffix='.7z';;
+        *.rpm) suffix='.rpm';;
+        *.deb) suffix='.deb';;
+        *.udeb) suffix='.udeb';;
+        *.iso) suffix='.iso';;
+        *.cpio) suffix='.cpio';;
+    esac
+
+    echo $suffix
+}
+
+
+detect_container() {
+    container="$1"; shift
+
+    typecode='<unknown>'
+    declare -a flags
+    # This is needed due to how the bash 'read' function works
+    # Without it the first word of unpack_cmd is eaten as the value of flags
+    flags=('__placeholder_flag=1')
+
+    suffix=$(detect_suffix "$container")
+    if [ -n "$guess" ]; then
+        mimetype=$(file -z --mime-type --brief "$container")
+        case "$mimetype" in
+            application/zip) typecode=zip;;
+            application/x-tar) typecode=tar;;
+        esac
+
+        [ "$typecode" != '<unknown>' ] && verbose "$container: guessed type '$typecode'"
+    fi
+
+    # Typecode not detected based on mime_type, try to match the suffix
+    if [ "$typecode" = '<unknown>' -a "$suffix" != '<unknown>' ]; then
+        # Assign typecode based on suffix
+        case "$suffix" in
+            .zip) typecode=zip;;
+            .rar) typecode=rar;;
+            .7z) typecode=7z;;
+            .cpio) typecode=cpio;;
+            .jar|.war|.ear) typecode=zip;;
+            .apk|.xapk|.ipa) typecode=zip;;
+            .docx) typecode=zip;;
+            .tar|.tar.gz|.tar.bz2|.tar.xz|.tgz|.tbz2) typecode='tar'; flags+=('auto_compress=1');;
+            .rpm) typecode=rpm;;
+            .deb|.udeb) typecode=dpkg;;
+            .iso) typecode=iso;;
+            .3mf) typecode=zip;;
+            *)  # This file is not an container we know, skip
+                error "$container: Skipping, not an container type we know"
+                ;;
+        esac
+    fi
+
+    # Assign variables based on typecode
+    case "$typecode" in
+        zip) unpack_cmd='[ -z "$verbose" ] && unzip_quiet_flag="-q"; unzip ${unzip_quiet_flag} -d "$unwrap_dir" "$container"';;
+        tar) unpack_cmd='tar -C "$unwrap_dir" ${auto_compress:+--auto-compress} -x${verbose:+v}f "$container"';;
+        rar) unpack_cmd='[ -z "$verbose" ] && unrar_quiet_flag="-inul"; unrar $unrar_quiet_flag x "$container" "$unwrap_dir/"';;
+        7z) unpack_cmd='if [ -z "$verbose" ]; then 7z x -o"$unwrap_dir" "$container" > /dev/null; else 7z x -o"$unwrap_dir" "$container"; fi';;
+        rpm) unpack_cmd='rpm2tar -O "$container" | tar -C "$unwrap_dir" -x${verbose:+v}';;
+        dpkg) unpack_cmd='dpkg-deb -x "$container"  "$unwrap_dir"';;
+        iso) unpack_cmd='if [ -z "$verbose" ]; then 7z x -o"$unwrap_dir" "$container" > /dev/null; else 7z x -o"$unwrap_dir" "$container"; fi';;
+        cpio) unpack_cmd='cpio -id${verbose:+}v "$unwrap_dir" < "$container"';;
+    esac
+
+    echo "$typecode $suffix $(join_by , $flags) $unpack_cmd"
+}
+
+
 while [ "$1" ]; do
     container="$1"; shift
 
     if [ -n "$hash_filename" ]; then
-        [ "$verbose" ] && echo "$container: Calculating SHA256 hash"
+        verbose "$container: Calculating SHA256 hash"
         sha256sum "$container" >> "$hash_filename"
     fi
 
-    # Detect suffix
-    case "$container" in
-	*.zip) suffix=".zip"; unpack_cmd='[ -z "$verbose" ] && unzip_quiet_flag="-q"; unzip ${unzip_quiet_flag} -d "$unwrap_dir" "$container"';;
-	*.jar) suffix=".jar"; unpack_cmd='[ -z "$verbose" ] && unzip_quiet_flag="-q"; unzip ${unzip_quiet_flag} -d "$unwrap_dir" "$container"';;
-	*.war) suffix=".war"; unpack_cmd='[ -z "$verbose" ] && unzip_quiet_flag="-q"; unzip ${unzip_quiet_flag} -d "$unwrap_dir" "$container"';;
-	*.ear) suffix=".ear"; unpack_cmd='[ -z "$verbose" ] && unzip_quiet_flag="-q"; unzip ${unzip_quiet_flag} -d "$unwrap_dir" "$container"';;
-	*.apk) suffix=".apk"; unpack_cmd='[ -z "$verbose" ] && unzip_quiet_flag="-q"; unzip ${unzip_quiet_flag} -d "$unwrap_dir" "$container"';;
-	*.xapk) suffix=".xapk"; unpack_cmd='[ -z "$verbose" ] && unzip_quiet_flag="-q"; unzip ${unzip_quiet_flag} -d "$unwrap_dir" "$container"';;
-	*.ipa) suffix=".ipa"; unpack_cmd='[ -z "$verbose" ] && unzip_quiet_flag="-q"; unzip ${unzip_quiet_flag} -d "$unwrap_dir" "$container"';;
-    *.docx) suffix=".docx"; unpack_cmd='[ -z "$verbose" ] && unzip_quiet_flag="-q"; unzip ${unzip_quiet_flag} -d "$unwrap_dir" "$container"';;
-	*.tar) suffix=".tar"; unpack_cmd='tar -C "$unwrap_dir" -x${verbose:+v}f "$container"';;
-	*.tar.gz) suffix=".tar.gz"; unpack_cmd='tar -C "$unwrap_dir" -xz${verbose:+v}f "$container"';;
-	*.tar.bz2) suffix=".tar.bz2"; unpack_cmd='tar -C "$unwrap_dir" -xj${verbose:+v}f "$container"';;
-	*.tar.xz) suffix=".tar.xz"; unpack_cmd='xz --decompress --stdout "$container" | tar -C "$unwrap_dir" -x${verbose:+v}';;
-	*.tgz) suffix=".tgz"; unpack_cmd='tar -C "$unwrap_dir" -xz${verbose:+v}f "$container"';;
-	*.tbz2) suffix=".tbz2"; unpack_cmd='tar -C "$unwrap_dir" -xj${verbose:+v}f "$container"';;
-	*.rar) suffix=".rar"; unpack_cmd='[ -z "$verbose" ] && unrar_quiet_flag="-inul"; unrar $unrar_quiet_flag x "$container" "$unwrap_dir/"';;
-	*.7z) suffix='.7z'; unpack_cmd='if [ -z "$verbose" ]; then 7z x -o"$unwrap_dir" "$container" > /dev/null; else 7z x -o"$unwrap_dir" "$container"; fi';;
-  *.rpm) suffix='.rpm'; unpack_cmd='rpm2tar -O "$container" | tar -C "$unwrap_dir" -x${verbose:+v}';;
-  *.deb) suffix='.deb'; unpack_cmd='dpkg-deb -x "$container"  "$unwrap_dir"';;
-  *.udeb) suffix='.udeb'; unpack_cmd='dpkg-deb -x "$container"  "$unwrap_dir"';;
-  *.iso) suffix='.iso'; unpack_cmd='if [ -z "$verbose" ]; then 7z x -o"$unwrap_dir" "$container" > /dev/null; else 7z x -o"$unwrap_dir" "$container"; fi';;
-	*.cpio) suffix='.cpio'; unpack_cmd='cpio -id${verbose:+}v "$unwrap_dir" < "$container"';;
-	*)  # This file is not an container we know, skip
-	    echo "$container: Skipping, not an container type we know"
-	    continue;;
-    esac
+    detect_container "$container" | ( read typecode suffix flags unpack_cmd
 
-    container_dir="$(basename "$container" "$suffix")"
-    unwrap_dir="$destdir/$container_dir"
-    [ "$verbose" ] && echo "$container: Unwrapping files into '$unwrap_dir'"
-    mkdir -p "$unwrap_dir" && unwrap_dir=$unwrap_dir container=$container eval $unpack_cmd
+        if [ "$typecode" != '<unknown>' -a "$suffix" != '<unknown>' ]; then
+            if [ -n "$flags" ]; then
+                set -o allexport
+                . <(echo $flags | sed 's/,/\n/')
+                set +o allexport
+            fi
 
-    # Check for asdf.zip containing asdf/ which gets unwrapped into asdf/asdf/
-    if find "$unwrap_dir" -maxdepth 1 -mindepth 1 -type d -name "$container_dir" | grep -q "$container_dir/$container_dir"; then
-        # Remove unneeded directory
-        ( shopt -s dotglob; mv "$unwrap_dir/$container_dir"/* "$unwrap_dir/" )
-        rmdir "$unwrap_dir/$container_dir" || ( echo "Someting is very wrong, '$unwrap_dir/$container_dir' should be empty"; exit 1 )
-    fi
+            container_dir="$(basename "$container" "$suffix")"
+            unwrap_dir="$destdir/$container_dir"
+            verbose "$container: Unwrapping files into '$unwrap_dir'"
+            echo "unpack cmd $unpack_cmd" 1>&2
+            mkdir -p "$unwrap_dir" && unwrap_dir=$unwrap_dir container=$container eval $unpack_cmd || error "$container: failed unpack_cmd '$unpack_cmd'"
 
-    # Search for other containers inside the extracted container
-    [ "$unwrap_once" ] || find "$unwrap_dir" -type f | while read file; do
+            # Check for asdf.zip containing asdf/ which gets unwrapped into asdf/asdf/
+            if find "$unwrap_dir" -maxdepth 1 -mindepth 1 -type d -name "$container_dir" | grep -q "$container_dir/$container_dir"; then
+                # Remove unneeded directory
+                ( shopt -s dotglob; mv "$unwrap_dir/$container_dir"/* "$unwrap_dir/" )
+                rmdir "$unwrap_dir/$container_dir" || ( echo "Someting is very wrong, '$unwrap_dir/$container_dir' should be empty"; exit 1 )
+            fi
 
-	# Optimize this on Cygwin by performing the suffix check now without running the command recursively
-	# fork() on Cygwin is very slow
+            # Search for other containers inside the extracted container
+            [ "$unwrap_once" ] || find "$unwrap_dir" -type f | while read file; do
+                    detect_container "$file" | ( read typecode suffix flags unpack_cmd
+                        if [ "$typecode" != '<unknown>' -a "$suffix" != '<unknown>' ]; then
+                            container_dir=$(dirname "$file")
+		                        unwrap -C "$container_dir" ${verbose:+-v} ${remove_container:+-x} ${guess:+-G} ${use_mimetype:+-m} ${hash_filename:+-H "$hash_filename"} "$file"
+                        else
+                            if [ -n "$hash_filename" ]; then
+                                verbose "$file: Calculating SHA256 hash"
+                                sha256sum "$file" >> "$hash_filename"
+                            fi
+                        fi
+                    )
+            done
 
-	case "$file" in
-	    *.zip|*.jar|*.tar|*.apk|*.xapk|*.ipa|*.docx|*.tar.gz|*.tar.bz2|*.tar.xz|*.tgz|*.tbz2|*.rar|*.7z|*.rpm|*.deb|*.udeb|*.iso|*.cpio)
-          container_dir=$(dirname "$file")
-		      unwrap -C "$container_dir" ${hash_filename:+-H "$hash_filename"} ${remove_container:+-x} "$file";;
-      *)
-          if [ -n "$hash_filename" ]; then
-              [ "$verbose" ] && echo "$file: Calculating2 SHA256 hash"
-              sha256sum "$file" >> "$hash_filename"
-          fi
-          ;;
-	esac
-    done
+            [ "$remove_container" ] && rm "$container"
 
-    [ "$remove_container" ] && rm "$container"
+        else
+            error "$container: skipping, not a container type we know"
+        fi
+    )
 done
